# Generated by Django 4.2 on 2023-04-28 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('num_huespedes', models.PositiveIntegerField()),
                ('tipo_habitacion', models.CharField(max_length=50)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('C', 'Confirmada'), ('P', 'Pendiente'), ('X', 'Cancelada')], max_length=1)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.hotel')),
            ],
        ),
    ]
